const U={s:"7e7a0001-8a5c-4d21-9b44-12d0a35d0001",st:"7e7a0002-8a5c-4d21-9b44-12d0a35d0001",r:"7e7a0003-8a5c-4d21-9b44-12d0a35d0001",g:"7e7a0004-8a5c-4d21-9b44-12d0a35d0001",c:"7e7a0005-8a5c-4d21-9b44-12d0a35d0001"};
let dev,st,r,g,c,logging=false,lastStatus={},track=JSON.parse(localStorage.getItem("adas_track")||"[]");
const $=x=>document.getElementById(x),dec=new TextDecoder(),enc=new TextEncoder();
const map=L.map("map").setView([10.8231,106.6297],13);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap"}).addTo(map);
let line,marker;
function log(x){$("log").textContent=new Date().toLocaleTimeString()+" "+x+"\n"+$("log").textContent}
function draw(){if(line)line.remove();line=L.polyline(track.map(p=>[p.lat,p.lon])).addTo(map)}
function status(d){lastStatus=d;$("risk").textContent=d.risk??"—";$("distance").textContent=(d.distance_m??"—")+" m";$("closing").textContent=(d.closing_kmh??"—")+" km/h";$("angle").textContent=(d.angle_deg??"—")+"°"}
function gps(d){$("fix").textContent=d.fix?"OK":"NO";$("sats").textContent=d.sats??"—";$("speed").textContent=(d.speed_kmh??"—")+" km/h";$("coords").textContent=d.lat!=null?`${d.lat}, ${d.lon}`:"—";if(d.fix){let p=[+d.lat,+d.lon];if(marker)marker.setLatLng(p);else marker=L.marker(p).addTo(map);if(logging){track.push({t:new Date().toISOString(),lat:+d.lat,lon:+d.lon,speed_kmh:+(d.speed_kmh||0),...lastStatus});localStorage.setItem("adas_track",JSON.stringify(track));draw()}}}
async function connect(){try{dev=await navigator.bluetooth.requestDevice({filters:[{services:[U.s]}]});dev.addEventListener("gattserverdisconnected",()=>{$("connect").disabled=false;$("disconnect").disabled=true;log("Disconnected")});let sv=await dev.gatt.connect(),svc=await sv.getPrimaryService(U.s);[st,r,g,c]=await Promise.all([svc.getCharacteristic(U.st),svc.getCharacteristic(U.r),svc.getCharacteristic(U.g),svc.getCharacteristic(U.c)]);await st.startNotifications();st.addEventListener("characteristicvaluechanged",e=>status(JSON.parse(dec.decode(e.target.value))));await g.startNotifications();g.addEventListener("characteristicvaluechanged",e=>gps(JSON.parse(dec.decode(e.target.value))));status(JSON.parse(dec.decode(await st.readValue())));gps(JSON.parse(dec.decode(await g.readValue())));$("connect").disabled=true;$("disconnect").disabled=false;$("readcfg").disabled=false;$("writecfg").disabled=false;await readcfg();log("BLE connected")}catch(e){log(e.message)}}
async function readcfg(){let d=JSON.parse(dec.decode(await r.readValue()));$("range").value=d.range_m;$("warn").value=d.ttc_warn;$("critical").value=d.ttc_critical}
async function writecfg(){let d=JSON.stringify({range_m:+$("range").value,ttc_warn:+$("warn").value,ttc_critical:+$("critical").value});await r.writeValue(enc.encode(d));log("Config "+d)}
function exportGeo(){let f=[];if(track.length)f.push({type:"Feature",properties:{kind:"route"},geometry:{type:"LineString",coordinates:track.map(p=>[p.lon,p.lat])}});track.forEach(p=>f.push({type:"Feature",properties:{time:p.t,risk:p.risk,speed_kmh:p.speed_kmh,distance_m:p.distance_m,closing_kmh:p.closing_kmh,angle_deg:p.angle_deg},geometry:{type:"Point",coordinates:[p.lon,p.lat]}}));let b=new Blob([JSON.stringify({type:"FeatureCollection",features:f},null,2)],{type:"application/geo+json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="adas-trip.geojson";a.click()}
$("connect").onclick=connect;$("disconnect").onclick=()=>dev?.gatt?.disconnect();$("readcfg").onclick=readcfg;$("writecfg").onclick=writecfg;$("start").onclick=()=>{logging=true;$("start").disabled=true;$("stop").disabled=false};$("stop").onclick=()=>{logging=false;$("start").disabled=false;$("stop").disabled=true};$("clear").onclick=()=>{track=[];localStorage.removeItem("adas_track");draw()};$("export").onclick=exportGeo;draw();log("Web ready");
